# `deque`

### LEVEL 1: The Basics (No dataset yet)
Goal: Understand how deque works, how it’s different from lists, and how to manipulate it.

### Skills:
- Creating a deque
- Using append(), appendleft()
- Using pop(), popleft()
- Checking maxlen
- Rotating the deque



In [1]:
from collections import deque, defaultdict
import pandas as pd
import math

### **1.1: Simple `deque` Creation**

**Problem**: Create a deque from the list `[1, 2, 3]`. Append 4 at the end. Append 0 at the beginning.

**Expected Output**:

```python
deque([0, 1, 2, 3, 4])
```

In [2]:
dq = deque([1, 2, 3])

In [3]:
dq.append(4)

In [4]:
dq.appendleft(0)

In [5]:
dq

deque([0, 1, 2, 3, 4])

### **1.2: Popping Elements**

**Problem**: From the deque above, remove an item from the right (`pop`) and the left (`popleft`).

**Expected Output**:

```python
Removed from right: 4
Removed from left: 0
Remaining deque: deque([1, 2, 3])
```

In [6]:
dq.pop()

4

In [7]:
dq.popleft()

0

In [8]:
dq

deque([1, 2, 3])

### **1.3: Fixed-Length `deque`**

**Problem**: Create a deque with `maxlen=3`. Append 10, 20, 30, then 40. What happens?

**Expected Output**:

```python
deque([20, 30, 40])
```

In [9]:
dq2 = deque(maxlen=3)

In [10]:
dq2.append(10)

In [11]:
dq2

deque([10], maxlen=3)

In [12]:
dq2.append(20)

In [13]:
dq2

deque([10, 20], maxlen=3)

In [14]:
dq2.append(30)

In [15]:
dq2

deque([10, 20, 30], maxlen=3)

In [16]:
dq2.append(40)

In [17]:
dq2

deque([20, 30, 40], maxlen=3)

**Explanation**: `deque` automatically removes the oldest item when full.



### **1.4: Rotate Right**

**Problem**: Rotate the deque `[1, 2, 3, 4, 5]` two steps to the right.

**Expected Output**:

```python
deque([4, 5, 1, 2, 3])
```


### What does rotate() do?
The `rotate(n)` method shifts all elements in the deque:

- If n > 0: rotates to the right
- If n < 0: rotates to the left

In [18]:
dq3 = deque([1, 2, 3, 4, 5])

In [19]:
dq3.rotate(2)

In [20]:
dq3

deque([4, 5, 1, 2, 3])

### What happened here?
Initially: [1, 2, 3, 4, 5]

- After rotating 1 step right: [5, 1, 2, 3, 4]
- After rotating another step right: [4, 5, 1, 2, 3]
- So the last two elements wrap around to the front.

### **1.5: Rotate Left**

**Problem**: Rotate the same deque two steps to the left.

**Expected Output**:

```python
deque([3, 4, 5, 1, 2])
```


In [21]:
dq4 = deque([1, 2, 3, 4, 5])

In [22]:
dq4.rotate(-2)

In [23]:
dq4

deque([3, 4, 5, 1, 2])

## LEVEL 2: Simulating Buffers and History (No real dataset yet)

**Goal**: Practice sliding windows, buffering, and rollbacks.

### Skills:

* Using `deque(maxlen=N)` to track last N items
* Using `appendleft()` to undo
* Accessing items like a list


### **2.1: Last 3 Processed Items**

**Problem**: Simulate a buffer tracking the last 3 parts that passed QA: 'P1', 'P2', 'P3', 'P4'

**Expected Output**:

```python
deque(['P2', 'P3', 'P4'], maxlen=3)
```

In [24]:
dq_buffer = deque(['P1', 'P2', 'P3', 'P4'], maxlen=3)

In [25]:
dq_buffer

deque(['P2', 'P3', 'P4'], maxlen=3)

### **2.2: Undo the Last Action**

**Problem**: Use `appendleft()` to push back 'P4' after it was mistakenly popped.

**Expected Output**:

```python
deque(['P4', 'P2', 'P3'], maxlen=3)
```

In [26]:
dq_buffer.appendleft('P4')

In [27]:
dq_buffer

deque(['P4', 'P2', 'P3'], maxlen=3)

### **2.3: History Tracker**

**Problem**: Maintain the last 5 temperature readings in a machine: `[78, 79, 80, 81, 82, 83]`

**Expected Output**:

```python
deque([79, 80, 81, 82, 83], maxlen=5)
```


In [28]:
dq_temp = deque([78, 79, 80, 81, 82, 83], maxlen=5)

In [29]:
dq_temp

deque([79, 80, 81, 82, 83], maxlen=5)

### **2.4: Sum of Last N**

**Problem**: Calculate the sum of the last 3 added values: `[5, 6, 7, 8]` → use `deque(maxlen=3)`.

**Expected Output**:

```python
Sum of last 3: 21  # (6+7+8)
```

In [30]:
dq_sum = sum(deque([5, 6, 7, 8], maxlen=3))

In [31]:
dq_sum

21

### **2.5: Use as Stack**

**Problem**: Simulate a stack with `deque`. Push: `A, B, C`. Pop 1.

**Expected Output**:

```python
deque(['A', 'B'])
```

In [32]:
dq_stack = deque(['A', 'B', 'C'])

In [33]:
dq_stack.pop()

'C'

In [34]:
dq_stack

deque(['A', 'B'])


### Recap: What a Stack Does

* Think of a stack like a pile of plates.
* You `push()` to add to the top (use `append()`).
* You `pop()` to remove the top item (use `pop()`).


### Why this matters:

`deque` is faster than a list for stack operations because:

* `pop()` and `append()` on the **right end** are O(1) (very efficient).
* Python’s list `pop()` from the front is O(n), which is slower.

This makes `deque` a smart choice for real-time processing systems, parsers, or undo-redo logic in GUIs.



### **2.6: Use as Queue**

**Problem**: Simulate a queue with `deque`. Enqueue: `X, Y, Z`. Dequeue 1 (left).

**Expected Output**:

```python
deque(['Y', 'Z'])
```

In [35]:
dq_q = deque(['X', 'Y', 'Z'])

In [36]:
dq_q.popleft()

'X'

In [37]:
dq_q

deque(['Y', 'Z'])

### **2.7: Peek First/Last**

**Problem**: Add items `[100, 200, 300]` to a deque. Print first and last without removing.

**Expected Output**:

```python
First: 100
Last: 300
```

In [38]:
dq_peek = deque([100, 200, 300])

In [39]:
first = dq_peek[0]

In [40]:
first

100

In [41]:
last = dq_peek[-1]

In [42]:
last

300

## LEVEL 3: With Simulated Mini-Dataset

We’re now transitioning from `deque` mechanics to **real-world simulation**, where each `deque` operation mimics a machine collecting sensor readings over time — just like what you'd encounter in injection molding or process control systems.



### Simulated Dataset:

We'll simulate **temperature readings** from a molding machine over time.

```python
temperature_readings = [68, 70, 72, 75, 74, 73, 76, 77, 80, 78]
```



### Skills You'll Practice:

* Using `deque(maxlen=N)` for sliding window
* Calculating **rolling average**
* Detecting spikes or drops
* Rolling back and resetting
* Handling stream-like input

## Exercise 3.1: Sliding Average (Window of 3)

**Problem**: For each new temperature reading, maintain the last 3 values and compute the **average**.

**Use**: `deque(maxlen=3)`

In [43]:
temperature_readings = [68, 70, 72, 75, 74, 73, 76, 77, 80, 78]

In [44]:
window = deque(maxlen=3)

In [45]:
for reading in temperature_readings:
    window.append(reading)
    avg = round(sum(window) / len(window), 2)
    print(f'Reading {reading} -> Widow: {list(window)} -> Average: {avg}')

Reading 68 -> Widow: [68] -> Average: 68.0
Reading 70 -> Widow: [68, 70] -> Average: 69.0
Reading 72 -> Widow: [68, 70, 72] -> Average: 70.0
Reading 75 -> Widow: [70, 72, 75] -> Average: 72.33
Reading 74 -> Widow: [72, 75, 74] -> Average: 73.67
Reading 73 -> Widow: [75, 74, 73] -> Average: 74.0
Reading 76 -> Widow: [74, 73, 76] -> Average: 74.33
Reading 77 -> Widow: [73, 76, 77] -> Average: 75.33
Reading 80 -> Widow: [76, 77, 80] -> Average: 77.67
Reading 78 -> Widow: [77, 80, 78] -> Average: 78.33


### Why It Matters:

* In manufacturing, **sliding window averages** help detect **drift** or **instability** in processes.
* We discard old values and keep only the **most recent N** values — this is where `deque(maxlen=N)` 

## **Exercise 3.2: Detect Spike or Drop**

### Problem:

Using the same readings list:

```python
temperature_readings = [68, 70, 72, 75, 74, 80, 65, 78]
```

Create a `deque(maxlen=3)` to track the latest readings.
If the new reading is more than **5 units higher or lower** than the average of the window, print a **"Spike" or "Drop" warning**.



In [46]:
temperature_readings = [68, 70, 72, 75, 74, 80, 65, 78]

In [47]:
window = deque(maxlen=3)

In [48]:
for reading in temperature_readings:
    window.append(reading)
    avg = round(sum(window) / len(window), 2)
    
    if abs(reading - avg) > 5:
        print(f'Spike/Drop Detected! Reading: {reading} -> Window: {list(window)} -> Average: {avg}')
    else:
        print(f'Reading: {reading} -> Window: {list(window)} -> Average: {avg}')

Reading: 68 -> Window: [68] -> Average: 68.0
Reading: 70 -> Window: [68, 70] -> Average: 69.0
Reading: 72 -> Window: [68, 70, 72] -> Average: 70.0
Reading: 75 -> Window: [70, 72, 75] -> Average: 72.33
Reading: 74 -> Window: [72, 75, 74] -> Average: 73.67
Reading: 80 -> Window: [75, 74, 80] -> Average: 76.33
Spike/Drop Detected! Reading: 65 -> Window: [74, 80, 65] -> Average: 73.0
Reading: 78 -> Window: [80, 65, 78] -> Average: 74.33


## **Exercise 3.3: Sliding Max/Min**

### **Problem**:

Given the following temperature readings:

```python
temperature_readings = [68, 70, 72, 75, 74, 80, 65, 78]
```

Use `deque(maxlen=3)` to keep a **sliding window** of the last 3 readings.
For each new reading, print the **maximum** and **minimum** values in the current window.


### **Goal Output Format**:

```
Reading: 68 → Window: [68] → Min: 68, Max: 68  
Reading: 70 → Window: [68, 70] → Min: 68, Max: 70  
Reading: 72 → Window: [68, 70, 72] → Min: 68, Max: 72  
Reading: 75 → Window: [70, 72, 75] → Min: 70, Max: 75  
...
```


In [49]:
temperature_readings = [68, 70, 72, 75, 74, 80, 65, 78]

In [50]:
window = deque(maxlen=3)

In [51]:
for reading in temperature_readings:
    window.append(reading)
    max_val = max(window)
    min_val = min(window)
    
    print(f'Reading {reading} -> Window: {list(window)} -> Max: {max_val}, Min: {min_val}')

Reading 68 -> Window: [68] -> Max: 68, Min: 68
Reading 70 -> Window: [68, 70] -> Max: 70, Min: 68
Reading 72 -> Window: [68, 70, 72] -> Max: 72, Min: 68
Reading 75 -> Window: [70, 72, 75] -> Max: 75, Min: 70
Reading 74 -> Window: [72, 75, 74] -> Max: 75, Min: 72
Reading 80 -> Window: [75, 74, 80] -> Max: 80, Min: 74
Reading 65 -> Window: [74, 80, 65] -> Max: 80, Min: 65
Reading 78 -> Window: [80, 65, 78] -> Max: 80, Min: 65


## **Exercise 3.4: Track Deviation from Rolling Average**

### **Problem**:

Given this temperature stream:

```python
temperature_readings = [68, 70, 72, 75, 74, 80, 65, 78]
```

Use `deque(maxlen=3)` to track a **rolling average**, and for each reading, calculate the **deviation** from that average.


### **What to Print**:

For each reading, output:

* The current window
* The rolling average
* The deviation (reading − average)


### **What You'll Learn**:

* How to track whether the **current reading is above or below** the recent trend.
* This is foundational for **anomaly detection** or **feedback control**.



### Sample Output:

```
Reading: 68 → Window: [68] → Avg: 68.00 → Deviation: 0.00  
Reading: 70 → Window: [68, 70] → Avg: 69.00 → Deviation: 1.00  
Reading: 72 → Window: [68, 70, 72] → Avg: 70.00 → Deviation: 2.00  
Reading: 75 → Window: [70, 72, 75] → Avg: 72.33 → Deviation: 2.67  
...
```

### Real-World Analogy:

In injection molding, if the **current mold temperature** is constantly **above the average**, it may be a signal of a machine drift, faulty cooling, or buildup in the mold cavity.



In [52]:
temperature_readings = [68, 70, 72, 75, 74, 80, 65, 78]

In [53]:
window = deque(maxlen=3)

In [54]:
for reading in temperature_readings:
    window.append(reading)
    avg = round(sum(window) / len(window), 2)
    deviation = round((reading - avg), 2)
    if deviation < 0:
        print(f'Reading {reading} -> Window: {list(window)} -> Average: {avg} -> Deviation: {deviation} -> ALERT: Machine Drift, Faulty Cooling or Cavity Buildup')
    else:
        print(f'Reading {reading} -> Window: {list(window)} -> Average: {avg} -> Deviation: {deviation}')
    

Reading 68 -> Window: [68] -> Average: 68.0 -> Deviation: 0.0
Reading 70 -> Window: [68, 70] -> Average: 69.0 -> Deviation: 1.0
Reading 72 -> Window: [68, 70, 72] -> Average: 70.0 -> Deviation: 2.0
Reading 75 -> Window: [70, 72, 75] -> Average: 72.33 -> Deviation: 2.67
Reading 74 -> Window: [72, 75, 74] -> Average: 73.67 -> Deviation: 0.33
Reading 80 -> Window: [75, 74, 80] -> Average: 76.33 -> Deviation: 3.67
Reading 65 -> Window: [74, 80, 65] -> Average: 73.0 -> Deviation: -8.0 -> ALERT: Machine Drift, Faulty Cooling or Cavity Buildup
Reading 78 -> Window: [80, 65, 78] -> Average: 74.33 -> Deviation: 3.67


## 🔧 **Exercise 3.5: Trigger Reset on Critical Reading**


### **Problem**:

If any temperature reading is **below 60**, it’s considered **a critical failure**.
In that case, **clear the sliding window** using `window.clear()`.


### Expected Output:

```
Reading: 68 → Window: [68]
Reading: 70 → Window: [68, 70]
Reading: 72 → Window: [68, 70, 72]
Reading: 75 → Window: [70, 72, 75]
Reading: 74 → Window: [72, 75, 74]
❌ CRITICAL! Reading: 59 → RESETTING buffer.
Reading: 65 → Window: [65]
Reading: 78 → Window: [65, 78]
```



### Why This Matters:

* Real systems often **reset** when an unsafe value is detected.
* Clearing the `deque` simulates dumping the faulty buffer so **new readings start fresh**.



In [55]:
temperature_readings = [68, 70, 72, 75, 74, 59, 65, 78]

In [56]:
window = deque(maxlen=3)

In [57]:
for reading in temperature_readings:
    if reading < 60:
        print(f'❌ CRITICAL! Reading {reading} -> Window: {list(window)}')
        window.clear()
    else:
        print(f'Reading: {reading} -> Window: {list(window)}')
        window.append(reading)

Reading: 68 -> Window: []
Reading: 70 -> Window: [68]
Reading: 72 -> Window: [68, 70]
Reading: 75 -> Window: [68, 70, 72]
Reading: 74 -> Window: [70, 72, 75]
❌ CRITICAL! Reading 59 -> Window: [72, 75, 74]
Reading: 65 -> Window: []
Reading: 78 -> Window: [65]


## **Exercise 3.6: Simulate Live Stream with Rolling Window**

### **Problem**:

Simulate a **live data stream** (e.g., every second or minute) where temperature values arrive continuously.

Using a `deque(maxlen=5)`, keep the latest **5 readings** and compute:

* **Rolling average**
* **Latest reading**
* Whether it’s **increasing** or **decreasing**



### Simulated Stream (can grow later):

```python
temperature_stream = [68, 69, 70, 72, 75, 77, 76, 78, 80, 79, 77]
```



### **Expected Print Format**:

```
Reading: 75 → Window: [70, 72, 75] → Avg: 72.33 → Trend: ↑
Reading: 76 → Window: [72, 75, 76] → Avg: 74.33 → Trend: ↑
Reading: 74 → Window: [75, 76, 74] → Avg: 75.00 → Trend: ↓
```


### What You’re Learning:

* Simulating live sensor input (streaming-style)
* Maintaining history while analyzing
* Using **trend direction** for dashboards and alerts

This is exactly how many **real-time monitoring dashboards** behave in production lines.



In [58]:
temperature_stream = [68, 69, 70, 72, 75, 77, 76, 78, 80, 79, 77]

In [59]:
window = deque(maxlen=5)

In [60]:
prev = None

In [61]:
for reading in temperature_stream:
    window.append(reading)
    avg = round(sum(window) / len(window), 2)
    
    if prev is None:
        trend = '↔ (No Prev)'
    elif reading > prev:
        trend = '↑'
    elif reading < prev:
        trend = '↓'
    else:
        trend = '→ (No Change)'
        
    print(f'Reading: {reading} -> Window: {window} -> Average: {avg} -> Trend: {trend}')
    prev = reading

Reading: 68 -> Window: deque([68], maxlen=5) -> Average: 68.0 -> Trend: ↔ (No Prev)
Reading: 69 -> Window: deque([68, 69], maxlen=5) -> Average: 68.5 -> Trend: ↑
Reading: 70 -> Window: deque([68, 69, 70], maxlen=5) -> Average: 69.0 -> Trend: ↑
Reading: 72 -> Window: deque([68, 69, 70, 72], maxlen=5) -> Average: 69.75 -> Trend: ↑
Reading: 75 -> Window: deque([68, 69, 70, 72, 75], maxlen=5) -> Average: 70.8 -> Trend: ↑
Reading: 77 -> Window: deque([69, 70, 72, 75, 77], maxlen=5) -> Average: 72.6 -> Trend: ↑
Reading: 76 -> Window: deque([70, 72, 75, 77, 76], maxlen=5) -> Average: 74.0 -> Trend: ↓
Reading: 78 -> Window: deque([72, 75, 77, 76, 78], maxlen=5) -> Average: 75.6 -> Trend: ↑
Reading: 80 -> Window: deque([75, 77, 76, 78, 80], maxlen=5) -> Average: 77.2 -> Trend: ↑
Reading: 79 -> Window: deque([77, 76, 78, 80, 79], maxlen=5) -> Average: 78.0 -> Trend: ↓
Reading: 77 -> Window: deque([76, 78, 80, 79, 77], maxlen=5) -> Average: 78.0 -> Trend: ↓


## **Exercise 3.7: Save and Rollback**

### Goal:

Simulate a situation where we:

* Continuously track readings using `deque(maxlen=5)`
* Make a **copy of the buffer** at a certain point
* Detect a fault (e.g., sudden drop), and **restore** from the saved state (rollback)



### Problem:

From the readings below:

```python
temperature_stream = [68, 70, 72, 75, 74, 59, 78, 79]
```

1. Save the window after reaching the 5th reading.
2. If a reading is below **60**, treat it as a fault:

   * Clear the window
   * Restore from the backup

### Expected Output:

```
Reading: 74 → Window: [68, 70, 72, 75, 74] → Avg: 71.80  
💾 Backup saved: [68, 70, 72, 75, 74]
❌ Fault Detected at 59. Rolling back...
Reading: 59 → Window: [68, 70, 72, 75, 74] → Avg: 71.80  
Reading: 78 → Window: [70, 72, 75, 74, 78] → Avg: 73.80
...
```



### Why It Matters:

This pattern is extremely useful when:

* You need **temporary state preservation** (like checkpoints)
* Handling **rollback** in dashboards or control loops
* Replaying the last known good configuration


In [62]:
temperature_stream = [68, 70, 72, 75, 74, 59, 78, 79]

In [63]:
window = deque(maxlen=5)

In [64]:
backup = None

In [65]:
for i, reading in enumerate(temperature_stream):
    window.append(reading)
    
    if i == 4:
        backup = window.copy()
        print(f'Backup saved: {list(backup)}')

    if reading < 60:
        print(f' XXX Fault Detected! at Reading: {reading}. Rolling back ...')
        window = backup.copy()
        
    avg = round(sum(window) / len(window), 2)
    
    print(f'Reading: {reading} -> Window: {window} -> Average: {avg}')

Reading: 68 -> Window: deque([68], maxlen=5) -> Average: 68.0
Reading: 70 -> Window: deque([68, 70], maxlen=5) -> Average: 69.0
Reading: 72 -> Window: deque([68, 70, 72], maxlen=5) -> Average: 70.0
Reading: 75 -> Window: deque([68, 70, 72, 75], maxlen=5) -> Average: 71.25
Backup saved: [68, 70, 72, 75, 74]
Reading: 74 -> Window: deque([68, 70, 72, 75, 74], maxlen=5) -> Average: 71.8
 XXX Fault Detected! at Reading: 59. Rolling back ...
Reading: 59 -> Window: deque([68, 70, 72, 75, 74], maxlen=5) -> Average: 71.8
Reading: 78 -> Window: deque([70, 72, 75, 74, 78], maxlen=5) -> Average: 73.8
Reading: 79 -> Window: deque([72, 75, 74, 78, 79], maxlen=5) -> Average: 75.6


## **Exercise 3.8: Multiple Sliding Windows (Parallel Sensor Monitoring)**

### **Problem**:

You have two parallel sensors:

* **Temperature** readings
* **Pressure** readings

Simulate both streams with synchronized sliding windows using two `deque(maxlen=3)` objects.
For each time step, compute the **rolling average** of both temperature and pressure.



### 🔧 Sample Streams:

```python
temperature_stream = [68, 70, 72, 75, 74, 76]
pressure_stream    = [102, 101, 100, 99, 101, 102]
```

### Sample Output:

```
Temp: 68 → [68] → Avg: 68.00 | Pres: 102 → [102] → Avg: 102.00  
Temp: 70 → [68, 70] → Avg: 69.00 | Pres: 101 → [102, 101] → Avg: 101.50  
Temp: 72 → [68, 70, 72] → Avg: 70.00 | Pres: 100 → [102, 101, 100] → Avg: 101.00  
...
```



### Real-World Relevance:

This simulates **multiple sensor tracks**, such as:

* **Melt temperature** + **Injection pressure**
* **Cycle time** + **Cooling water temp**
* Or any time-synchronized multi-parameter data

You can even extend this to dictionaries and timestamps later.



In [66]:
temperature_stream = [68, 70, 72, 75, 74, 76]
pressure_stream    = [102, 101, 100, 99, 101, 102]

In [67]:
temp_window = deque(maxlen=5)

In [68]:
press_window = deque(maxlen=5)

In [69]:
for temp, press in zip(temperature_stream, pressure_stream):
    temp_window.append(temp)
    press_window.append(press)
    
    temp_avg = round(sum(temp_window) / len(temp_window), 2)
    press_avg = round(sum(press_window) / len(press_window), 2)
    
    print(f'Temp: {temp} -> {list(temp_window)} -> Average: {temp_avg} | Press: {press} -> {list(press_window)} -> Average: {press_avg}')

Temp: 68 -> [68] -> Average: 68.0 | Press: 102 -> [102] -> Average: 102.0
Temp: 70 -> [68, 70] -> Average: 69.0 | Press: 101 -> [102, 101] -> Average: 101.5
Temp: 72 -> [68, 70, 72] -> Average: 70.0 | Press: 100 -> [102, 101, 100] -> Average: 101.0
Temp: 75 -> [68, 70, 72, 75] -> Average: 71.25 | Press: 99 -> [102, 101, 100, 99] -> Average: 100.5
Temp: 74 -> [68, 70, 72, 75, 74] -> Average: 71.8 | Press: 101 -> [102, 101, 100, 99, 101] -> Average: 100.6
Temp: 76 -> [70, 72, 75, 74, 76] -> Average: 73.4 | Press: 102 -> [101, 100, 99, 101, 102] -> Average: 100.6


## **Exercise 3.9: Record Peak + Timestamp using Tuples**

### **Problem**:

Simulate a sensor that records `(timestamp, value)` tuples.
Use `deque(maxlen=5)` to maintain the **last 5 readings**, and print the **highest reading so far**, along with its timestamp.



### Sample Input (timestamp, temperature):

```python
temperature_stream = [
    ("08:00", 68),
    ("08:01", 70),
    ("08:02", 72),
    ("08:03", 75),
    ("08:04", 74),
    ("08:05", 76),
    ("08:06", 73)
]
```




### Expected Output:

```
Reading: (08:00, 68) → Window: [('08:00', 68)] → Peak: 68 at 08:00  
Reading: (08:01, 70) → Window: [('08:00', 68), ('08:01', 70)] → Peak: 70 at 08:01  
Reading: (08:02, 72) → ... → Peak: 72 at 08:02  
Reading: (08:03, 75) → ... → Peak: 75 at 08:03  
Reading: (08:04, 74) → ... → Peak: 75 at 08:03  
Reading: (08:05, 76) → ... → Peak: 76 at 08:05  
Reading: (08:06, 73) → ... → Peak: 76 at 08:05  
```



### What You’ve Just Learned:

* Storing **structured data** in a `deque` (not just numbers!)
* Using `max()` with a custom `key` to extract **peaks from tuples**
* Tracking both **value and time** for better diagnostics and reporting

This is exactly how timestamped logs are summarized in real dashboards and quality control tools!

In [70]:
temperature_stream = [
    ("08:00", 68),
    ("08:01", 70),
    ("08:02", 72),
    ("08:03", 75),
    ("08:04", 74),
    ("08:05", 76),
    ("08:06", 73)
]

In [71]:
window = deque(maxlen=5)

In [72]:
for timestamp, temp in temperature_stream:
    window.append((timestamp, temp))
    
    peak = max(window, key=lambda x: x[1])
    # What max() Does:
    # max(iterable, key=...) goes through each element in the iterable (here: deque) and uses the key function to decide how to compare elements.
    # The key=lambda x: x[1] means:
    # "Compare each tuple using only the temperature value (x[1]) to find the maximum."
    # Similar Usage:
    # min(window, key=lambda x: x[1])    # Find min temperature
    # sorted(window, key=lambda x: x[1]) # Sort by temperature
    
    print(f'Reading: {(timestamp, temp)} -> Window: {list(window)} -> Peak: {peak[1]} at {peak[0]}')

Reading: ('08:00', 68) -> Window: [('08:00', 68)] -> Peak: 68 at 08:00
Reading: ('08:01', 70) -> Window: [('08:00', 68), ('08:01', 70)] -> Peak: 70 at 08:01
Reading: ('08:02', 72) -> Window: [('08:00', 68), ('08:01', 70), ('08:02', 72)] -> Peak: 72 at 08:02
Reading: ('08:03', 75) -> Window: [('08:00', 68), ('08:01', 70), ('08:02', 72), ('08:03', 75)] -> Peak: 75 at 08:03
Reading: ('08:04', 74) -> Window: [('08:00', 68), ('08:01', 70), ('08:02', 72), ('08:03', 75), ('08:04', 74)] -> Peak: 75 at 08:03
Reading: ('08:05', 76) -> Window: [('08:01', 70), ('08:02', 72), ('08:03', 75), ('08:04', 74), ('08:05', 76)] -> Peak: 76 at 08:05
Reading: ('08:06', 73) -> Window: [('08:02', 72), ('08:03', 75), ('08:04', 74), ('08:05', 76), ('08:06', 73)] -> Peak: 76 at 08:05


## **Exercise 3.10: Sliding Variance and Anomaly Flagging**

### **Problem**:

Using a sliding window of the last 5 temperature readings, calculate:

* **Rolling average**
* **Rolling variance**
* Flag readings that **deviate from the mean by more than 1.5× standard deviation**



### Concepts:

* **Mean (μ)** = average of the values
* **Variance (σ²)** = average of squared differences from the mean
* **Standard Deviation (σ)** = √variance
* A value is considered **anomalous** if:

  $$
  |reading - \mu| > 1.5 \cdot \sigma
  $$



### Sample Readings:

```python
temperature_readings = [68, 70, 72, 75, 74, 80, 65, 78]
```

### Sample Output:

```
Reading: 68 → Window: [68] (waiting for more data...)
Reading: 70 → Window: [68, 70] → Avg: 69.00 → Std Dev: 1.00 → Deviation: 1.00
Reading: 72 → Window: [68, 70, 72] → Avg: 70.00 → Std Dev: 1.63 → Deviation: 2.00
Reading: 75 → Window: [68, 70, 72, 75] → Avg: 71.25 → Std Dev: 2.59 → Deviation: 3.75 ⚠️ Anomaly
...
```



### Skills Learned:

* Calculate variance and standard deviation using `deque`
* Detect **outliers in real-time**
* Build a framework for intelligent QA/SCADA alerting logic




In [73]:
temperature_readings = [68, 70, 72, 75, 74, 80, 65, 78]

In [74]:
window = deque(maxlen=5)

In [75]:
for reading in temperature_readings:
    window.append(reading)
    
    if len(window) >= 2:
        mean = sum(window) / len(window)
        variance = sum((x - mean) ** 2 for x in window) / len(window)
        std_dev = math.sqrt(variance)
        
        deviation = abs(reading - mean)
        is_anomaly = deviation > 1.5 * std_dev
        
        print(f'Reading: {reading} -> Window: {list(window)} -> {"⚠️ Anomaly" if is_anomaly else "" }')
    else:
        print(f'Reading: {reading} -> Window: {list(window)} (waiting for more data.....)')
    
    

Reading: 68 -> Window: [68] (waiting for more data.....)
Reading: 70 -> Window: [68, 70] -> 
Reading: 72 -> Window: [68, 70, 72] -> 
Reading: 75 -> Window: [68, 70, 72, 75] -> 
Reading: 74 -> Window: [68, 70, 72, 75, 74] -> 
Reading: 80 -> Window: [70, 72, 75, 74, 80] -> ⚠️ Anomaly
Reading: 65 -> Window: [72, 75, 74, 80, 65] -> ⚠️ Anomaly
Reading: 78 -> Window: [75, 74, 80, 65, 78] -> 


# 🏭 **LEVEL 4: Real Dataset – Injection Molding (365 Days)**

> `injection_mold_365day_dataset.csv`



## 🔍 Step 1: What We’ll Do in Level 4

| Exercise | Title                                                | Focus                                   |
| -------- | ---------------------------------------------------- | --------------------------------------- |
| 4.1      | Load and Inspect Dataset                             | Understand structure + preview          |
| 4.2      | Rolling Average per Field (Temperature, Pressure...) | `deque(maxlen=5)` for each sensor       |
| 4.3      | Detect Outliers from Rolling Mean                    | Compare live vs. mean (threshold logic) |
| 4.4      | Flag Simultaneous Spikes in Multiple Fields          | Parallel deque tracking                 |
| 4.5      | Rolling Mean + Variance Dashboard                    | Combine stats for real monitoring       |
| 4.6      | Record Critical Events (Timestamp + Field + Value)   | Save anomalies as logs (tuples)         |
| 4.7      | Reset Window After Shutdown                          | Clear `deque` on reset trigger          |
| 4.8      | Compare Current Week vs Last Week Stats              | Weekly deque sliding comparison         |



## 🧪 Exercise 4.1: Load and Inspect Dataset

Let’s begin by loading and previewing the dataset.
### What to Look For:

* Which fields are numeric (e.g. `Temperature`, `Pressure`, `CycleTime`, etc.)
* Do we have a `Date` or `Time` field?
* Any missing or suspicious values?


In [76]:
df = pd.read_csv('injection_mold_365day_dataset.csv')

In [77]:
df.columns.to_list()

['Date',
 'Shift',
 'Mold ID',
 'Part Name',
 'Wear Level (%)',
 'Surface Roughness (Ra μm)',
 'Clearance (mm)',
 'Alignment Accuracy (mm)',
 'Leak Check',
 'Corrosion',
 'Crack Detected',
 'Function Test',
 'Lubrication Status',
 'Pass/Fail']

In [78]:
numeric_cols = df.select_dtypes(include='number').columns.tolist()

In [79]:
numeric_cols

['Wear Level (%)',
 'Surface Roughness (Ra μm)',
 'Clearance (mm)',
 'Alignment Accuracy (mm)']

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2190 entries, 0 to 2189
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Date                       2190 non-null   object 
 1   Shift                      2190 non-null   object 
 2   Mold ID                    2190 non-null   object 
 3   Part Name                  2190 non-null   object 
 4   Wear Level (%)             2190 non-null   float64
 5   Surface Roughness (Ra μm)  2190 non-null   float64
 6   Clearance (mm)             2190 non-null   float64
 7   Alignment Accuracy (mm)    2190 non-null   float64
 8   Leak Check                 2190 non-null   object 
 9   Corrosion                  1658 non-null   object 
 10  Crack Detected             2190 non-null   object 
 11  Function Test              2190 non-null   object 
 12  Lubrication Status         2190 non-null   object 
 13  Pass/Fail                  2190 non-null   objec

In [81]:
df.head(5)

Date    Shift  Mold ID       Part Name  Wear Level (%)  \
0  2025-01-01  Shift 1  MOLD741       Guide Pin            60.8   
1  2025-01-01  Shift 1  MOLD742      Core Plate            43.5   
2  2025-01-01  Shift 1  MOLD560  Runner Channel            15.0   
3  2025-01-01  Shift 2  MOLD126  Support Pillar            68.7   
4  2025-01-01  Shift 2  MOLD727      Core Plate            53.7   

   Surface Roughness (Ra μm)  Clearance (mm)  Alignment Accuracy (mm)  \
0                       1.03           0.323                    0.076   
1                       0.28           0.339                    0.188   
2                       0.57           0.418                    0.128   
3                       0.47           0.109                    0.045   
4                       0.41           0.351                    0.181   

  Leak Check Corrosion Crack Detected Function Test Lubrication Status  \
0       Pass    Severe             No          Fail      Needs Reapply   
1       Pass  Moderate            Yes          Fail               Good   
2       Fail  Moderate            Yes          Pass      Needs Reapply   
3       Pass  Moderate             No          Pass               Good   
4       Fail  Moderate            Yes          Fail      Needs Reapply   

  Pass/Fail  
0      Fail  
1      Fail  
2      Pass  
3      Pass  
4      Fail

## **Exercise 4.2: Rolling Average per Numeric Field**

### Goal:

Use `deque(maxlen=5)` to calculate the **5-day rolling average** for each of the following fields:

* Wear Level (%)
* Surface Roughness (Ra μm)
* Clearance (mm)
* Alignment Accuracy (mm)


### Sample Output:

```
Date: 01-01 → Wear Level (%) Avg: 60.80 | Surface Roughness (Ra μm) Avg: 1.03 | ...
Date: 01-02 → Wear Level (%) Avg: 52.15 | Surface Roughness (Ra μm) Avg: 0.66 | ...
...
```



### 🧠 What You’re Learning:

* Applying `deque` to multiple fields simultaneously
* Building a rolling analytics tool over real manufacturing data
* Prepping for anomaly detection based on rolling metrics

In [82]:
fields = numeric_cols

In [83]:
fields

['Wear Level (%)',
 'Surface Roughness (Ra μm)',
 'Clearance (mm)',
 'Alignment Accuracy (mm)']

In [84]:
rolling_windows = {field: deque(maxlen=5) for field in fields}

In [86]:
for idx, row in df.iterrows():
    output = [f'Date: {row["Date"]}']
    
    for field in fields:
        value = row[field]
        rolling_windows[field].append(value)
        avg = sum(rolling_windows[field]) / len(rolling_windows[field])
        output.append(f'{field} Avg: {avg:.2f}')
        
    print(' | '.join(output))
    
    if idx == 9:  # preview first 10 rows
        break

Date: 2025-01-01 | Wear Level (%) Avg: 60.80 | Surface Roughness (Ra μm) Avg: 1.03 | Clearance (mm) Avg: 0.32 | Alignment Accuracy (mm) Avg: 0.08
Date: 2025-01-01 | Wear Level (%) Avg: 52.15 | Surface Roughness (Ra μm) Avg: 0.66 | Clearance (mm) Avg: 0.33 | Alignment Accuracy (mm) Avg: 0.13
Date: 2025-01-01 | Wear Level (%) Avg: 39.77 | Surface Roughness (Ra μm) Avg: 0.63 | Clearance (mm) Avg: 0.36 | Alignment Accuracy (mm) Avg: 0.13
Date: 2025-01-01 | Wear Level (%) Avg: 47.00 | Surface Roughness (Ra μm) Avg: 0.59 | Clearance (mm) Avg: 0.30 | Alignment Accuracy (mm) Avg: 0.11
Date: 2025-01-01 | Wear Level (%) Avg: 48.34 | Surface Roughness (Ra μm) Avg: 0.55 | Clearance (mm) Avg: 0.31 | Alignment Accuracy (mm) Avg: 0.12
Date: 2025-01-01 | Wear Level (%) Avg: 38.40 | Surface Roughness (Ra μm) Avg: 0.49 | Clearance (mm) Avg: 0.25 | Alignment Accuracy (mm) Avg: 0.14
Date: 2025-01-02 | Wear Level (%) Avg: 43.48 | Surface Roughness (Ra μm) Avg: 0.47 | Clearance (mm) Avg: 0.28 | Alignment Ac